esphome:
  name: nibe-complete
  friendly_name: Nibe Gateway Complete

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

# Static IP configuration
ethernet:
  type: DM9051
  clk_pin: GPIO7
  mosi_pin: GPIO10
  miso_pin: GPIO3
  cs_pin: GPIO9
  interrupt_pin: GPIO8
  reset_pin: GPIO6
  clock_speed: 8MHz
  manual_ip:
    static_ip: 192.168.1.34
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
  use_address: 192.168.1.34

uart:
  id: nibe_uart
  rx_pin: GPIO21
  tx_pin: GPIO20
  baud_rate: 9600

external_components:
  - source:
      type: git
      url: https://github.com/yourusername/esphome-nibe-idf.git
    components: [nibegw]

nibegw:
  id: nibe_gw
  uart_id: nibe_uart
  
  dir_pin:
    number: GPIO19
    inverted: false
  
  udp:
    target:
      - ip: 192.168.1.100
        port: 9999
    source:
      - 192.168.1.100
    read_port: 9999
    write_port: 10000
  
  # Acknowledge both MODBUS40 and enable virtual RMU on S1
  acknowledge:
    - MODBUS40
    - RMU40_S1
  
  # Required constant responses
  constants:
    # MODBUS40 version
    - address: MODBUS40
      token: ACCESSORY
      data: [0x0A, 0x00, 0x02]
    
    # RMU40 S1 accessory version
    - address: RMU40_S1
      token: ACCESSORY
      data: [0xEE, 0x03, 0x01]
    
    # RMU40 S1 data response
    - address: RMU40_S1
      token: RMU_DATA
      command: RMU_WRITE
      data: [0x63, 0x00]
    
    # RMU40 S1 fixed temperature (prevents alarm)
    - address: RMU40_S1
      token: RMU_WRITE
      data: [0x06, 0x14, 0x00]  # 20°C

# Virtual RMU40 climate entity for System 1
climate:
  - platform: nibegw
    name: "Living Room Climate"
    gateway: nibe_gw
    system: 1  # S1
    sensor: living_room_temp

# Temperature sensor from Home Assistant
sensor:
  - platform: homeassistant
    id: living_room_temp
    entity_id: sensor.living_room_temperature
    
  - platform: uptime
    name: "Uptime"
    
  - platform: internal_temperature
    name: "MCU Temperature"

# Status sensors
text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "IP Address"
    
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: status
    name: "Status"

# Restart button
button:
  - platform: restart
    name: "Restart"